export  const data = [
    {title:"人格特質測驗＋JS考古題" , hackMD:"https://hackmd.io/Z5wZE0f7QJK2yFfC2oc65A" , Codepen:null },
    {title:"課前 Day 2｜ ES6 物件解構與強化" ,hackMD:"https://hackmd.io/N5wSVYrHR5u1kkMaRMCWHg?view" , Codepen:"https://codepen.io/kunpao0104/pen/mdxBJow"},
    {title:"課前 Day 3｜ ES6 陣列解構與強化" , hackMD:"https://hackmd.io/qroTYRa_TVSSgvHUAALZMg" , Codepen:"https://codepen.io/kunpao0104/pen/bGvoJJp" },
    {title:"課前 Day 4｜JavaScript 展開與其餘" , hackMD:"https://hackmd.io/rC55tBk0Qtyjq-eApUeZMw" , Codepen:"https://codepen.io/kunpao0104/pen/JjLOKYd" },
    {title:"課前 Day 5｜常見 JS 陣列方法練習" , hackMD:"https://hackmd.io/dCnz5QdZQp-oJuqR0IJFqg" , Codepen:"https://codepen.io/kunpao0104/pen/zYWPLOX" },
    {title:"Day 1｜ React JSX" , hackMD:"https://hackmd.io/8oroP7oJSS6gqN-ykcbn9A?view" , Codepen:"https://codepen.io/kunpao0104/pen/VwXQKJd" },
    {title:"Day 2｜ JSX 屬性練習" , hackMD:"https://hackmd.io/yBagsoeCSkKEQ-jXvLpqag?view" , Codepen:"https://codepen.io/kunpao0104/pen/eYMVBpv" },
    {title:"Day 3｜ React Hook - useState" , hackMD:"https://hackmd.io/EJQ12mm_SIu9BtNqpHNGeg?view" , Codepen:"https://codepen.io/kunpao0104/pen/KKoomNp" },
    {title:"Day 4｜React Hook - useState 進階練習" , hackMD:"https://hackmd.io/YG83weiMQtG7EZailLq0bQ?view" , Codepen:"https://codepen.io/kunpao0104/pen/ExEEmvv" },
    {title:"Day 5｜React Hook - useEffect" , hackMD:"https://hackmd.io/lGayE3kzT-qfUnAgpPSReQ?view" , Codepen:"https://codepen.io/kunpao0104/pen/RwMyXGa" },
    {title:"第一週課綱 React 起手式，從 Hooks 開始入門" , hackMD:"https://hackmd.io/EYEIimtpQH6rETHtlvLEgg" , Codepen:"https://codepen.io/kunpao0104/pen/rNddrVp" },
    {title:"Day 6｜ Raect Hook - useEffect 呼叫 API" , hackMD:"https://hackmd.io/htysRrOhQ4iQzk9qSh6Sfw?view" , Codepen:"https://codepen.io/kunpao0104/pen/WNzKvPW" },
    {title:"Day 7｜元件建立" , hackMD:"https://hackmd.io/gORV81mjQWmnviYie2XBnw?view" , Codepen:"https://codepen.io/kunpao0104/pen/ExEpVdQ" },
    {title:"Day 8｜ 元件整合練習" , hackMD:"https://hackmd.io/K62fIzZeTRi8r7UxSXvp0w?view" , Codepen:"https://codepen.io/kunpao0104/pen/abYRddE" },
    {title:"Day 9｜元件 props 資料傳遞" , hackMD:"https://hackmd.io/4xV05GEoQECiEI3lkVKzLA?view" , Codepen:"https://codepen.io/kunpao0104/pen/rNdqxdp" },
    {title:"Day 10｜ 元件陣列資料 props 傳遞" , hackMD:"https://hackmd.io/1gouMJamQj6zQSX-Ym04cg?view" , Codepen:"https://codepen.io/kunpao0104/pen/QWmZNbq" },
    {title:"第二週課綱 Component 元件開發" , hackMD:"https://hackmd.io/8M7VYdBAQJqcnZMatyc42Q?view" , Codepen:"https://codepen.io/kunpao0104/pen/KKoGmaQ" },
    {title:"Day 11｜元件 props 事件處理" , hackMD:"https://hackmd.io/W1wee-fpT5aBqHIWlERBCQ" , Codepen:"https://codepen.io/kunpao0104/pen/dymQQbY" },
    {title:"Day 12｜React Hook - useContext" , hackMD:"https://hackmd.io/UWHU1d57TPKjRPhxZPr9sA" , Codepen:"https://codepen.io/kunpao0104/pen/QWmYGME" },
    {title:"Day 13｜React Router 建立" , hackMD:"https://hackmd.io/VqEGaLa7TAW41hKsWZp4kA" , Codepen:"https://codepen.io/kunpao0104/pen/KKoJLVd" },
    {title:"Day 14｜React Router" , hackMD:"https://hackmd.io/2PcaYppLQlCmx7eldhTJ1w" , Codepen:"https://codepen.io/kunpao0104/pen/wvmNbML" },
    {title:"Day 15｜React Router 動態路由" , hackMD:"https://hackmd.io/F3UphiNUQx6XP5nXxhCOEQ" , Codepen:"https://codepen.io/kunpao0104/pen/vYRbwGz" },
    {title:"第三週課綱 React Router 設計" , hackMD:"https://hackmd.io/qijzvN_YQUCIYz4cADe4_w" , Codepen:"https://github.com/neko0104/react-daily-task-router" },
    {title:"Day 16｜React Hook Form - required" , hackMD:"https://hackmd.io/v5gALNn4R2it5FzooT2sew" , Codepen:"https://codepen.io/kunpao0104/pen/MWVRwry" },
    {title:"Day 17｜React Hook Form - email, password" , hackMD:"https://hackmd.io/cBGCCAQTT_WZEYcKrd5taA" , Codepen:"https://codepen.io/kunpao0104/pen/JjLQoyq" },
    {title:"Day 18｜React Hook Form - Submit Form" , hackMD:"https://hackmd.io/PfhXp-a1QxiCgkk6XYoGmg" , Codepen:"https://codepen.io/kunpao0104/pen/NWYZPmy" },
    {title:"Day 19｜axios headers token settings" , hackMD:"https://hackmd.io/neQCMjvQSQC0kG6arpf0Mw" , Codepen:"https://codepen.io/kunpao0104/pen/wvmLqeg" },
    {title:"Day 20｜React Deploy" , hackMD:"https://hackmd.io/hgeS_jgrQDWGdlHNy-216g" , Codepen:"https://codepen.io/kunpao0104/pen/zYWVdmb" },
    {title:"第四週 Todolist 全攻略" , hackMD:"https://hackmd.io/qAoC1rc2TyqLl_io39Du8Q?view" , Codepen:"" },

]